# Generated by Django 2.1.1 on 2020-02-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='tables',
            field=models.ManyToManyField(to='menus.Table'),
        ),
    ]
