# Generated by Django 3.0.4 on 2020-03-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
