# Generated by Django 2.1.1 on 2020-03-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0002_auto_20200227_1537'),
        ('users', '0003_auto_20200316_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pending', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customuser')),
                ('food_items', models.ManyToManyField(null=True, to='menus.MenuItem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
                ('tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Table')),
            ],
        ),
    ]
