# Generated by Django 2.1.1 on 2020-03-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(blank=True, to='menus.MenuItem'),
        ),
    ]
