# Generated by Django 2.1.1 on 2020-03-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200316_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
